config/routes.rb
Rails.application.routes.draw do
  # Devise routes for authors
  devise_for :authors, controllers: {
    registrations: 'authors/registrations'
  }

  # Resource routes for authors and books
  resources :authors, only: [:show]
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root 'home#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/book.rb
class Book < ApplicationRecord

  filterrific(
        
    available_filters: [
      
        :search_query,
        :search_release_date,
        :search_author_name
        ]
    )

    def self.search_query(query)
    where('title LIKE ?', "%#{query}%")
    end

    def self.search_release_date(query)
        # puts query
        where('release_date = ?', "%#{query}%")
    end

    def self.search_author_name(query)
        joins(:author).where('authors.name LIKE ?', "%#{query}%")
    end

    def self.to_csv(collection)
      CSV.generate(col_sep: ';') do |csv|
        csv << ['Title', 'Release Date', 'Author Name']
        collection.find_each do |record|
          csv << [record.title, record.release_date, record.author.name]
        end
      end
    end

  belongs_to :author
  validates :title, uniqueness: true
  validates :release_date, comparison: { less_than: -> { Date.current } }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    # def index 
    #     @books = Book.all
    # end
    before_action :authenticate_author!
    require 'csv'
    def index
        @filterrific = initialize_filterrific(
              Book,
              params[:filterrific]
            ) or return
            @books = if params[:filterrific].present? && (params[:filterrific][:search_query].present? || params[:filterrific][:search_release_date].present? || params[:filterrific][:search_author_name].present?)
                
                        # puts params[:filterrific]
                        @filterrific.find
                    else
                        Book.includes(:author).all
                    end
            respond_to do |format|
              format.html
              format.js
              format.csv do
                filename = ['Books', Date.today].join(' ')
                send_data Book.to_csv(@books), filename:, content_type: 'text/csv'
              end
            end
          end

    def new
        @book = Book.new
        @book.author_id = current_author.id
    end

    def create
        @book = Book.new(book_params)
        @book.author_id = current_author.id
      
        if @book.save
          redirect_to books_path
        else
            puts @book.errors.full_messages
            render :new
        end
    end

    def show
        @books = Book.find(params[:id])
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        @book = Book.find(params[:id])
        
        if @book.update(book_params)
            redirect_to book_path(@book)
        else
            flash[:error]   = @book.errors.full_messages
            render :edit
        end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end  

    private

    def book_params
        params.require(:book).permit(:title, :release_date, :author_id)
    end
end

app/views/books/edit.html.erb
<div class="container">
<%= form_with model: @book do |form| %>
    <div>
        <%= form.label :title %><br/>
        <%= form.text_field :title, class: 'text-field' %><br/>
    </div>
    <div>
        <%= form.label :release_date %><br/>
        <%= form.text_field :release_date, class: 'text-field' %><br/>
    </div>

    <div>
        <%= form.submit 'Submit', class:'button' %>
    </div>
<% end %>
</div>

app/views/books/index.html.erb
<div class="container">
  <h1>Listing All Books</h1>
  <div class="navbar">
    <%= link_to 'Home', root_path, class: 'button' %>
    <%= link_to 'Add a book', new_book_path, class: 'button' %>
    <%= link_to 'Download Books', books_path(format: :csv), class: 'button' %>
  </div>

  <%= form_for_filterrific @filterrific, url: books_path, html: { method: :get } do |f| %>
    <%= f.text_field :search_query, placeholder: 'Search by title' %>
    <%= f.text_field :search_release_date, placeholder: 'Search by release date' %>
    <%= f.text_field :search_author_name, placeholder: 'Search by author name' %>
    <%= f.submit 'Filter', class: 'button' %>
  <% end %>

  <table>
    <thead>
      <tr>
        <th>Book ID</th>
        <th>Book title</th>
        <th>Book Release Date</th>
        <th>Author Name</th>
        <th colspan="3">Book Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.id %></td>
          <td><%= book.title %></td>
          <td><%= book.release_date %></td>
          <td><%= book.author.name %></td>
          <td><%= link_to 'Details', book, class: 'button' %></td>
          <% if book.author == current_author %>
            <td><%= link_to 'Edit', edit_book_path(book), class: 'button' %></td>
            <td><%= button_to 'Delete', book, method: :delete, class: 'button' %></td>
          <% else %>
            <td></td>
            <td></td>
          <% end %>        
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/new.html.erb
<div class="container">
  <%= form_with model: @book do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title, class: 'text-field' %><br>
    </div>
    <div>
      <%= form.label :release_date %><br>
      <%= form.text_field :release_date, class: 'text-field' %><br>
    </div>
    <div>
      <%= form.label :author_id %><br>
      <%= form.text_field :author_id, class: 'text-field' %><br>
    </div>
    <div>
      <%= form.submit 'Submit', class: 'button' %>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="container">
<h1>Book details</h1><br/>

<h3><%= "Book ID: #{@books.id}" %></h3>
<h3><%= "Book title: #{@books.title}" %></h3>
<h3><%= "Book release_date: #{@books.release_date}" %></h3>
<h3><%= "Book auther_id: #{@books.author_id}" %></h3>
<div>
    <%= link_to 'Back', books_path, class:'button' %> 
    <% if @books.author == current_author %>
        <%= link_to 'Edit', edit_book_path(@books), class:'button' %>
    <% end %>
</div>
</div>